var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                        o                       ",
   "                                                                                ",
   "                                                                                ",
   "           o                          o                                         ",
   "                                         o                                      ",
   "           xxx                                   xxx         xxxx               ",
   "           xxx                                   xxx       xxxxxx               ",
   " @         xxx      xxxx    xx    xx    xxxx     xxx         xxxx               ",
   "xxxxx      xxx    xxx  xxx  xx    xx  xxx  xxx   xxx         xxxx  o    o       ",
   "xxx        xxx   xxxxxxxxx  xx    xx xxxxxxxxx   xxx         xxxx               ",
   "xxx        xxx   xxx         xx oxx  xxx         xxx         xxxx               ",
   "xxx        xxx    xx    xx    xxxx    xx    xx   xxx         xxxx               ",
   "xxx        xxx     xxxxxx      xx      xxxxxx    xxx       xxxxxxxx             ",
   "xxx                                                                             ",
   "xxxiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiixxxxx",
   "xxxiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiixxxxx",
   "xxxiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiixxxxx",
   "xxxiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiixxxxx",
   "xxxiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiixxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                      xiix                        xxxxxxx                                    xix  ",
   "                                      xiix                     xxxx     xxxx                                 xix  ",
   "                                      xiixxxxxxxxxx           xx           xx                                xix  ",
   "                                      xxiiiiiiiiiixx         xx             xx                               xix  ",
   "                                       xxxxxxxxxxiix         x                                    o   o   o  xix  ",
   "                                                xxix         x     o   o                                    xxix  ",
   "                                                 xix         x                                xxxxxxxxxxxxxxxiix  ",
   "                                                 xvx         x     x   x                        iiiiiiiiiiiiiixx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xxiiiiiiiiiiixx            v                        ",
   "                                                               xxxxiiiiixxxx                                      ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "iiiix xiiiiiix         xiiiiiixx     xxiiiiiiiixx    xiiiiiiiiii     x     =     x x         x                    ",
   "iiiix xiiiiiix         xiiiiixx       xxxxxxxxxx     xiiiiiiixxi     xxxxxxxxxxxxx xx  o o  xx                    ",
   "iiiix xiiiiiix         xiiiiix    o                 xxiiiiiixx i                    xx     xx                     ",
   "iiiix xiiiiiix         xiiiiix                     xxiiiiiixx  i                     xxxxxxx                      ",
   "iiiix xiiiiiix         xiiiiixx       xxxxxxxxxxxxxxiiiiiixx   i                                                  ",
   "iiiix xiiiiiix         xiiiiiixxxxxxxxxiiiiiiiiiiiiiiiiiixx    i                                                  ",
   "iiiix xiiiiiix         xiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiixx     i                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 iii        iii  xxx                                ",
   "                                       x x                 ixi        ixi                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      xiiix                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    xiiix                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           xiiix                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     xiiix                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 xiiix                  ",
   "                             xxx xxx xxx xxx     o o  xiiiiiiiiiiiiiix                   vx                   ",
   "                             x xxx x x xxx x          xiiiiiiiiiiiiiix                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         xiiix                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       xiiix          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           xiix    xiiiix    xiiiix    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       i  o  i                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       i  o  i            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xiiiiiiiiiiiiiiiiiiiiixxxiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
