var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                        o                       ",
   "                                                                                ",
   "                                                                                ",
   "           o                          o                                         ",
   "                                         o                                      ",
   "           xxx       L                           xxx         xxxx               ",
   "           xxx                                   xxx       xxxxxx               ",
   " @         xxx      xxxx    xx    xx    xxxx     xxx         xxxx               ",
   "xxxxxx     xxx    xxx  xxx  xx    xx  xxx  xxx   xxx         xxxx  o    o       ",
   "xxx        xxx   xxxxxxxxx  xx    xx xxxxxxxxx   xxx         xxxx               ",
   "xxx        xxx   xxx         xx oxx  xxx         xxx         xxxx               ",
   "xxx        xxx    xx    xx    xxxx    xx    xx   xxx         xxxx               ",
   "xxx        xxx     xxxxxx      xx      xxxxxx    xxx       xxxxxxxx         C   ",
   "xxx                                                                             ",
   "xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                ",
   "                                                                                ",
   "                   xxxxx                                     o                  ",
   "                   x!!!x                                                        ",
   "                   xxvxx                                                        ",
   "                                                                                ",
   "                     L                                                          ",
   "xxxxxx           o                  o       o                                   ",
   "xx   x                                            o                             ",
   "xx@  x                                                   xxxxx                  ",
   "xxxx x         xxx       xxx   xx        x               x!!!x                  ",
   "xxxx x                    xx  oxx!!!!!!!!x          xxxxxx!!!xxxxxx             ",
   "xxxx x                    xx  xxx!!!!!!!!x                 v                    ",
   "xxx       xxx             xxx  xxx!x!xxxxx                o                     ",
   "xxx  o                    xxo    x x x      xxxxx                               ",
   "xxx                       xx               xxxxxx       xx   xx                 ",
   "xxx  xxx                  xx              xxxxxxx                               ",
   "xxx                       xx             xxxxxxxx                               ",
   "xxx                       xx            xxxxxxxxx                            C  ",
   "xxx                       xxxxxxxx|x|xxxxxxxxxxxx                               ",
   "xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                       =",
   "                          vxxxxvxxxxvxxxxvxxxxvxxxxvxxxx                        ",
   "                                                       x                        ",
   "                                                            =                   ",
   "       o                                               x                        ",
   "      xxx              xxx   x   xxx xxxx xxxx xxx                             ",
   "                                                 xx    x                        ",
   "                         x       x               x                       =      ",
   "=            o                        xxx xxx   xx    xx                        ",
   "            xxx          x       x    x     x o  x                 =            ",
   "        =                             x    @xx   x  o  x                        ",
   "                         x       x    x x xxx    xx                             ",
   "      o                             o x         xx     x                        ",
   "     xxx                 x       x    x          x                    =         ",
   "                       =              xxx xxxx xxx    xx                        ",
   "                         x       x            o          =                      ",
   "                 o=                                                 o           ",
   "                xxx      x       xxx xxxx xxxx xxxx xxxx       o         o      ",
   "       L                                                                        ",
   "      xxx                                                                    C =",
   "=                        x xxxx xxxx xxxx xxxx xxxx xxxxxxx                     ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

];

!f (typeof module != "undef!ned" && module.exports)
  module.exports = GAME_LEVELS;
